version: '3.9'

services:
  myapp:
    build: ./myapp
    container_name: myapp
    restart: always
    ports:
      - '8000:8000'
  prometheus:
    image: prom/prometheus:v2.25.2
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    ports:
      - '9090:9090'
    restart: always

volumes:
  prometheus_data:
